
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MightyGoogle
 */
public class ListAllEmployeeInformation extends javax.swing.JFrame {
    private MyHashTable EmployeeHashTable;
    
    /**
     * Creates new form ListAllEmployeeInformation
     */
    public MyHashTable getTheHashTable() {
        return EmployeeHashTable;
    }
    
    public void setMainHT(MyHashTable theRefVal) {
        EmployeeHashTable = theRefVal;
    }
    
    public ListAllEmployeeInformation() throws FileNotFoundException {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(204, 255, 255));
        enterInfoIntoTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Number", "First name", "Last name", "gender", "work location", "Deduction rate", "Hourly wage", "Hours per Week", "Weeks per year"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Number", "First name", "Last name", "gender", "work location", "Deduction rate", "Salary"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jLabel1.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jLabel1.setText("Full-time Employee Information:");

        jLabel2.setFont(new java.awt.Font("American Typewriter", 1, 24)); // NOI18N
        jLabel2.setText("Part-time Employee Information:");

        jButton2.setIcon(new javax.swing.ImageIcon("/Users/MightyGoogle/NetBeansProjects/Employee_management_system/Icons/small house.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1263, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(354, 354, 354)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(432, 432, 432))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Homepage theHomepageWindow = new Homepage();
            theHomepageWindow.setVisible(true);
            MyHashTable refVal = getTheHashTable();
            theHomepageWindow.setMainHT(refVal);
            super.dispose();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PTEOrFTE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListAllEmployeeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListAllEmployeeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListAllEmployeeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListAllEmployeeInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ListAllEmployeeInformation().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ListAllEmployeeInformation.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public void enterInfoIntoTables() throws FileNotFoundException{
        String employeeNumber; String firstName = ""; String lastName = ""; String gender = ""; String workLocation = ""; String deductionRate = ""; String salary = "";
        String hourlyWage = ""; String hoursPerWeek = ""; String weeksPerYear = "";
        File FTEFile = new File("/Users/MightyGoogle/NetBeansProjects/Employee_management_system/FullTimeEmployeeData.txt");
        if(FTEFile.length() > 0){
            Scanner FTEscan = new Scanner(FTEFile);
            FTEscan.useDelimiter("[,\n]");
            
            DefaultTableModel defaultModel = (DefaultTableModel)jTable2.getModel();

            while(FTEscan.hasNext()){
                employeeNumber = FTEscan.next();
                firstName = FTEscan.next();
                lastName = FTEscan.next();
                gender = FTEscan.next();
                workLocation = FTEscan.next();
                deductionRate = FTEscan.next();
                salary = FTEscan.next();
                String addToTable[] = {employeeNumber, firstName, lastName, gender, workLocation, deductionRate, salary};
                
                defaultModel.addRow(new Object[]{employeeNumber, firstName, lastName, gender, workLocation, deductionRate, salary});
                
            }
            FTEscan.close();
        }

 
        File PTEFile = new File("/Users/MightyGoogle/NetBeansProjects/Employee_management_system/PartTimeEmployeeData.txt");
        if(PTEFile.length() > 0){

            Scanner PTEScan = new Scanner(PTEFile);
            PTEScan.useDelimiter("[,\n]");
            DefaultTableModel defaultModel2 = (DefaultTableModel)jTable1.getModel();

            while(PTEScan.hasNext()){
                employeeNumber = PTEScan.next();
                firstName = PTEScan.next();
                lastName = PTEScan.next();
                gender = PTEScan.next();
                workLocation = PTEScan.next();
                deductionRate = PTEScan.next();
                hourlyWage = PTEScan.next();
                hoursPerWeek = PTEScan.next();
                weeksPerYear = PTEScan.next();
                
                
                defaultModel2.addRow(new Object[]{employeeNumber, firstName, lastName, gender, workLocation, deductionRate, hourlyWage, hoursPerWeek, weeksPerYear});
   
            }
            PTEScan.close();
        }

        return;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
